config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :posts
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post 
end

app/models/post.rb
class Post < ApplicationRecord
	validates :content, presence: true, length: {maximum:140 }

	has_many :favorites, dependent: :destroy
	has_many :favorite_users, through: :favorites, source: :user
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  
  before_save { email.downcase! }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end 

  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
	    ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

    def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create 
    favorite = current_user.favorites.create(post_id: params[:post_id])
	redirect_to posts_url, notice: "#{favorite.post.user.name}のやつ気に入った"
  end

  def destroy
    favorite = current_user.favorites.find_by(post_id: params[:post_id]).destroy
	redirect_to post_url, notice: "#{favorite.post.user.name}のやつお気に入りじゃなかったわ"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  before_action :must_login, only: [:new, :edit, :show]
  def index
    # @posts = Post.all.order(created_at: :desc)
	  @posts = Post.page(params[:page]).per(5)
	  # @posts = Post.paginate(page: params[:page])
   @search = Post.ransack(params[:q])

   if params[:q].present?
     @search = Post.ransack(params[:q])
     @results = @search.result
    end
  # elsif params[:q].nill?

  end

  def show
    @post = Post.find_by(id: params[:id])
	@user = User.find_by(id: @post.user_id)
	@favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
	@post.user_id = current_user.id 

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'はいできました' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'かきかえた' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'けしたよ' }
      format.json { head :no_content }
    end
  end

  def ensure_current_user 
    @post = Post.find_by(id:params[:id])
	  if @post.user_id != @current_user.id 
	    flash[:notice] = 'ちがうだろ？'
		reidrect_to("/posts/index")
	  end
  end

  private
    def post_params
	  params.require(:post).permit(:content, :user_id, :blog_id)
	end

    def set_post
      @post = Post.find(params[:id])
    end

	def must_login
	  unless !current_user.nil?
	    redirect_to posts_path, notice: "ログインしないでいけると思ってんの？"
	  end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
	if user && user.authenticate(params[:session][:password])
	  session[:user_id] = user.id 
	  redirect_to user_path(user.id)
	else
	  render 'new', notice: "ダメだったな..."
	end
  end

  def destroy
    session.delete(:user_id)
	redirect_to new_session_path, notice: "はいできた"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new 
    @user = User.new 
  end

  def create
    @user = User.new(user_params)
	if @user.save
	  redirect_to user_path(@user.id)
	else
	  render 'new'
	end 
  end

  def show
    @user = User.find(params[:id])
	@favorite_posts = @user.favorite_posts
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
	  # redirect_to new_session_path, notice: "ログインしないでいけると思ってんの？"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twiclone</title>
    <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Bootstrap</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/posts">TwitterClone
            </a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="">top</a></li>
              <li><a href="">menu1</a></li>
              <li><a href="">menu2</a></li>
      		<li><a href="">menu3</a></li>
              <li><a href="">kani</a></li>
              <li><a href="">kanikani</a></li>
              <li><a href="">kanikanikani</a></li>
              <li><a href="">kanikanikanikani</a></li>
              <li><a href="">kanikanikanikanikani</a></li>
              <li><a href="">kanikanikanikanikanikani</a></li>
            </ul>
          </div>
        </div>
      </nav>


    <% if logged_in? %>
      <%= link_to "ようすをみる", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>


    <%= yield %>

    </div>

    <div class="space">
    </div>

    <footer>
      <p>かずー</p>
      <p>201711期受講生かずー</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" >
	 <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(post.errors.count, "エラー") %> でたから:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
	 </div>
    </div>
  <% end %>

  <div class="field post">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="actions">
    <%= form.submit "post", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
<h1>探して みました</h1>

	<!-- <table class="lists">
		<thread>
			<tr>
				<th colspan="3"></th>
			</tr>
		</thread> -->


				<% results.each do |post| %>
					  <div class="col-md-6 col-xs-12">
				      <table class="lists">
				        	<tr><%= post.content %></tr>
							<td><button type="button" class="btn btn-info"><%= link_to 'くわしく', post %></button></td>
					        <% if post.user_id == current_user.id %>
							  <td><button type="button" class="btn btn-warning"><%= link_to 'かきかえ', edit_post_path(post) %></button></td>
					          <td><button type="button" class="btn btn-danger"><%= link_to 'けす', post, method: :delete, data: { confirm: 'マジかよ...？' } %></button></td>
							<% end %>
				      </table>
						</div>
	  		<% end %>
			</div>

app/views/posts/edit.html.erb
<h1>かきなおし</h1>

<%= render 'form', post: @post %>

<button type="button" class="btn btn-default"><%= link_to 'くわしく', @post %></button>
<button type="button" class="btn btn-default"><%= link_to 'もどる', posts_path %></button>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>投稿っす</h1>
<%= paginate @posts %>

      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <div class="row">
          <% @posts.each do |post| %>
            <div class="col-md-6 col-xs-12">
            <table class="lists">
                <tr><%= post.content %></tr>
                <td><button type="button" class="btn btn-info"><%= link_to 'くわしく', post %></button></td>
			    <% if post.user_id == current_user.id %>
				  <td><button type="button" class="btn btn-warning"><%= link_to 'かきかえ', edit_post_path(post) %></button></td>
                  <td><button type="button" class="btn btn-danger"><%= link_to 'けす', post, method: :delete, data: { confirm: 'マジかよ...？' } %></button></td>
				<% end %>
            </table>
          </div>
          <% end %>
      </div>

<br>

<button type="button" class="btn btn-primary"><%= link_to 'あたらしいやつ', new_post_path %></button>
<!-- ここまででとりあえず完成 -->
<!-- 以下からransack実装テスト -->

<%= search_form_for @search do |f| %>
  <div class="form-group">
    <%= f.label :content_cont, "Content" %>
    <%= f.text_field :content_cont, class: "form-control" %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>
<p class="attn">なんも いれないで 検索 したら 全部 でます</p>

<% if @results.present? %>
  <%= render partial: "post", locals: { results: @results} %>
<% end %>

app/views/posts/new.html.erb
<h1>あたらしいやつ作成</h1>

<div class="form-group">
  <%= render 'form', post: @post %>
</div>
<button type="button" class="btn btn-primary"><%= link_to 'もどる', posts_path %></button>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>なかみ:</strong>
  <%= @post.content %>
</p>

<% unless @post.user == current_user %> 
  <% if @favorite.present? %>
    <%= link_to '気に入らない', favorite_path(post_id: @post.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to '気に入った', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end  %>

<%= link_to 'かきなおし', edit_post_path(@post), class: "test" %> |
<%= link_to 'もどる', posts_path, class: "test" %>

app/views/users/new.html.erb
<h2>新規の人か？</h2>

<h3>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</h3>


<%= form_with(model: @user, local: true) do |f| %>

  <div class='label'><%= f.label :name %></div>
  <%= f.text_field :name %>

  <div class='label'><%= f.label :email %></div>
  <%= f.email_field :email %>

  <div class='label'><%= f.label :password %></div>
  <%= f.password_field :password %>

  <div class='label'><%= f.label :password_confirmation %></div>
  <%= f.password_field :password_confirmation %>

  <br />

  <div class="space1">

  <%= f.submit "つくる", class: 'btn btn-success' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<P>メールアドレス：<%= @user.email %></P>

<h2><%= @user.name %>のお気に入りたち<h2>

<% @favorite_posts.each do |favorite_posts| %>
  <table>
    <tr><p>投稿者:<%= favorite_posts.user.name %></p></tr>
    <tr><p>ないよう:<%= favorite_posts.content %></p></tr>
  </table>
<% end %>


<%=link_to '投稿する', new_post_path, class: 'btn btn-success' %>